eigval_type: h

fitnames:
  - 250604-ac-02-L1

fitlabels:
  - "$h^{1}$"
  - "$h^{2}$"
  - "$h^{3}$"

fitcolors:
  - "C0"
  - "C1"
  - "C2"

eigvals:
  - 1
  - 2
  - 3

group_by: eigvals
ylabel: "$\\textrm{h}$"
